# Generated by `nuget-to-nix` 
# You may edit this file manually or update it with `nuget-to-nix` 
[
  {
    name = "System.IO.Ports";
    version = "7.0.0";
    # Empty array for packages without files
    files = [];
  }
]
